# Generated by Django 3.2.7 on 2022-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredmap_midwest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resort',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
