# Generated by Django 3.2.7 on 2022-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredmap_midwest', '0002_auto_20220204_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='groomer_review',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='lift_review',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='park_review',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='vibe_review',
            field=models.IntegerField(default=None),
        ),
    ]
